### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by skodapetr** [filipdbrsk/LOTUS_Search#2]
Files package.json and config.json (or at least an example) are missing.
It would also be great to add some installation guide.

**Comment by filievski** [comment]
Indeed, the installation guide and the file package.json were missing, now this should be improved. Let me know if the guide is unclear or you are getting errors when installing through package.json.

Regarding config.json, that file is where we keep our credentials for accessing the data in ElasticSearch. Note that the API should be used with one's own LOTUS index and one should use the variable query_url (https://github.com/filipdbrsk/LOTUS_Search/blob/master/server.js#L19) to point to one's own ElasticSearch endpoint. In this case, the config.json file is specific to our own instance here at the VU, and irrelevant to other installations.

Hope this helps!
